spring.application.name=all-micro-service
server.port=8080
spring.profiles.active=pro


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://mysql/student_db?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=admin123
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Enable JPA Transactions Debug logs
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.transaction=DEBUG
logging.level.org.springframework.orm.jpa.JPATransactionManager=DEBUG   

# Swagger UI path

# application.properties

# Max number of threads in Tomcat pool
server.tomcat.threads.max=200

server.tomcat.threads.min-spare=200

server.tomcat.accept-count=100

# Minimum number of threads always kept alive
server.tomcat.max-connections=8192

# Connection timeout in ms
server.tomcat.connection-timeout=20000


# Expose all actuator endpoints
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,metrics
server.tomcat.mbeanregistry.enabled=true
management.metrics.export.enabled=true


# Enable Prometheus-style metrics (if needed)
#management.endpoint.metrics.enabled=true
#management.endpoint.prometheus.enabled=true



